# Generated by Django 4.2 on 2023-04-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, unique=True, verbose_name='Título del Blog')),
                ('subtitulo', models.CharField(max_length=150, unique=True, verbose_name='SubTítulo del Blog')),
                ('cuerpo', models.TextField(max_length=10000, verbose_name='Texto/Descripción')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor')),
                ('imagen', models.ImageField(upload_to='')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado / No Publicado')),
                ('fecha_publicado', models.DateField(verbose_name='Fecha de Publicación')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=12)),
                ('cuerpo', models.CharField(max_length=10000)),
                ('fecha', models.DateField()),
                ('entregado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=12, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('contrasena', models.CharField(max_length=12, verbose_name='Contraseña')),
            ],
        ),
    ]
