# Generated by Django 4.2 on 2023-05-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen_portada',
            field=models.ImageField(blank=True, default="{% static 'images/cliente_feliz.jpg' %}", null=True, upload_to=''),
        ),
    ]
